### PR TITLE
Fix collisions of tables

### PR DESCRIPTION
**Pull request by lifeiscontent**
@benjie this fixed it for me, is there anything you'd like to bring up? sorry for the whitespace edits. I had prettier turned on.

### CODE REVIEW

**Comment by lifeiscontent** [comment]
@benjie for the record, it'd be really nice to have a test suite to test this kind of stuff, but postgraphile is bound to the DB right? Maybe we should implement a feature that allows you to mock the DB

**Comment by benjie** [comment]
We should be able to do that using the introspection cache 👍

**Comment by lifeiscontent** [comment]
@benjie awesome, would love to see how that would work. If you create a test harness, I'll start open sourcing some plugins! ;)

**Comment by benjie** [comment]
Yeah; I've been considering building a PostGraphile jest environment for a while.

These changes look good by the way; I'm surprised that I wasn't already formatting the code with prettier - I typically do that by default on all projects nowadays!

It's going to be a week before I get round to properly reviewing/merging this, there are a few other changes I want to make at the same time and get out in a new major version of this plugin. If you haven't heard back from me by Friday please give me a nudge.

**Pull request merged**
